#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

which bundle 2>&1 >/dev/null || {
  echo -e '\n== Please install bundle and then run the script again =='
  exit 1
}

which npm 2>&1 >/dev/null || {
  echo -e '\n== Please install npm and then run the script again =='
  exit 1
}

which grunt 2>&1 >/dev/null || {
  echo -e '\n== Installing grunt-cli =='
  npm install -g grunt-cli
}

bundle install
npm install
