#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

source script/_common

main_branch=dev
release_branch=master

__git-current-branch-or-exit $main_branch
__continue-prompt "Have you run '$ git pull origin $main_branch' (is your code up to date)?"

__exe_cmd "bundle exec jekyll build"
if [ ! -d '_site' ]; then
  echo "Jekyll build failed. Missing _site directory (no content to publish)"
  exit 1
fi

__exe_cmd "git checkout $release_branch"
error_code=$?
if [ $error_code != 0 ]; then
  echo 'Switch branch fail.'
  exit
else
  ls | grep -v _site | xargs rm -rf
  __exe_cmd "cp -r _site/* ."
  __exe_cmd "rm -rf _site/"
  __exe_cmd "touch .nojekyll"
  __exe_cmd "git add --all :/"
  __exe_cmd "git commit -m 'compile'"
  __exe_cmd "git push -f origin $release_branch"
  __exe_cmd "git checkout $main_branch"
fi

echo 'deployed: http://justarrived.se'
