#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

function exe_cmd() {
  echo $1
  eval $1
}

exe_cmd "bundle exec jekyll build"
if [ ! -d '_site' ]; then
  echo "missing _site directory (no content to publish)"
  exit
fi

branch=master

exe_cmd "git checkout $branch"
error_code=$?
if [ $error_code != 0 ]; then
  echo 'Switch branch fail.'
  exit
else
  ls | grep -v _site | xargs rm -rf
  exe_cmd "cp -r _site/* ."
  exe_cmd "rm -rf _site/"
  exe_cmd "touch .nojekyll"
  exe_cmd "git add --all :/"
  exe_cmd "git commit -m 'compile'"
  exe_cmd "git push origin master"
fi
