#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

source script/_common

post_to_slack() {
  local slack_webhook_url=${JUST_ARRIVED_SE_SLACK_DEPLOY_HOOK_URL:-}
  if [[ -z $slack_webhook_url ]]; then
    echo '[WARNING] JUST_ARRIVED_SE_SLACK_DEPLOY_HOOK_URL not set! Please set in order to post to Slack on deploy.'
  else
    local data='{"text": "A new version of <https://justarrived.se|justarrived.se> has been deployed.", "channel": "#website", "username": "just-bot", "icon_emoji": ":shipit:"}'

    echo 'Posting deploy to Slack..'
    curl -X POST -H 'Content-type: application/json' --data $data $slack_webhook_url > /dev/null 2>&1 &
  fi
}

origin="https://github.com/justarrived/justarrived.github.io/"
main_branch=siteleaf
release_branch=live

# __git-current-branch-or-exit $main_branch

__exe_cmd "bundle exec jekyll build --config=_config.yml"
if [ ! -d '_site' ]; then
  echo "Jekyll build failed. Missing _site directory (no content to publish)"
  exit 1
fi


REMOTE_REPOSITORY=${REMOTE_REPOSITORY:?'You need to configure the REMOTE_REPOSITORY environment variable!'}
REMOTE_BRANCH=${REMOTE_BRANCH:?'You need to configure the REMOTE_BRANCH environment variable!'}

git config --global user.email "$GIT_USER_EMAIL"
git config --global user.name "$GIT_USER_NAME"

__exe_cmd "git fetch --unshallow || true"
__exe_cmd 'git fetch origin "+refs/heads/*:refs/remotes/origin/*"' # see https://documentation.codeship.com/general/projects/push-to-remote-repositories/
# __exe_cmd "git checkout $release_branch"
error_code=$?
# if [ $error_code != 0 ]; then
#   echo 'Switch branch fail.'
#   exit
# else
  ls | grep -v _site | grep -v CNAME | xargs rm -rf
  __exe_cmd "cp -r _site/* ."
  __exe_cmd "rm -rf _site/"
  __exe_cmd "touch .nojekyll"
  __exe_cmd "git add --all :/"
  __exe_cmd "git commit -m 'compile'"
  __exe_cmd "git push -f "${REMOTE_REPOSITORY}" "${CI_COMMIT_ID}:${REMOTE_BRANCH}""
  # post_to_slack
  # __exe_cmd "git checkout $main_branch"
# fi
echo 'deployed: https://justarrived.se'
